# Copyright 2011 Vadim Vygonets. All rights reserved.
# Use of this source code is governed by the Bugroff
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=forth
GOFILES=vm.go kern.go
TARGDIR=..

include $(GOROOT)/src/Make.pkg
